### ISSUE TITLE
Does not work anymore

### ISSUE THREAD

**Issue by louis49** [farshid616/androidTV-controller-Python#1]
Since few weeks, the Android-TV never answer with len(message) > 4

Do you know where I can find Google specifications about that protocol ?

**Comment by farshid616** [comment]
First of all thank you for using this project.
Specification for this protocol is limited to google partners. I don't have that information too and I build this project based on a simple wiki. I'll check for the problem and I found something, I'll share it with you ;)

Can you just tell me which device and model you are using and facing this issue?

**Comment by louis49** [comment]
Hi, i was using Freebox Player Pop
I found the new protocol specifications and use it here : 
https://github.com/louis49/homebridge-plugin-androidtv
Don’t hesitate if you have questions
